### PR TITLE
#164047017 Setup environment for testing

### PR DESCRIPTION
**Pull request by winniekariuki**
#### Description 
configure enzyme and jest to run test

#### How Has This Been Tested?
run the following commands
#### Checklist:
- Tests run

#### Pivotal Tracker
[#164047017](https://www.pivotaltracker.com/story/show/164047017)

### CODE REVIEW

**Review by Kibetchirchir — COMMENTED** [review]
Good implementation

**Review by Kibetchirchir — APPROVED** [review]
Good implementation

**Comment by mnswaleh** [comment]
Screenshot 2019-04-02 at 14 24 22
am getting above error when I do `npm test`

**Comment by winniekariuki** [comment]
Please confirm that your package.json is in alignment with mine

**Comment by winniekariuki** [comment]
mnswaleh, please confirm that your package.json is in alignment with mine.

**Review by mnswaleh — APPROVED** [review]
Issue fixed

**Review by Derrickkip — APPROVED** [review]
LGTM and works as expected

**Pull request merged**
