### PR TITLE
#164047015 create react app

### PR DESCRIPTION
**Pull request by mnswaleh**
#### Description
creates an empty react app

#### How Has This Been Tested?
run the following commands
#### Checklist:
- Application starts

#### Pivotal Tracker
[#164047015](https://www.pivotaltracker.com/story/show/164047015)

### CODE REVIEW

**Review by JumaKahiga — APPROVED** [review]
The boilerplate looks good to me.

**Comment by winniekariuki** [comment]
Looks good to me.Detailed  comments

**Review by winniekariuki — APPROVED** [review]

**Comment by kelvinndmo** [comment]
Good setup.Looks good with the detailed comments.

**Comment by kelvinndmo** [comment]
Looks good with some good detailed comments

**Review by kelvinndmo — APPROVED** [review]

**Review by Derrickkip — APPROVED** [review]
Works as expected

**Pull request merged**
