### PR TITLE
#164047016 chore(setup redux): Set up redux file structure

### PR DESCRIPTION
**Pull request by kevpy**
## Description ##
This pull request creates the appropriate folder structure for working with redux as a state management store for React apps

## Type of change ##
Please select the relevant option
- [ ] Bug fix(a non-breaking change which fixes an issue)
- [x] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ##
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [ ] Integration test
- [ ] unit test

## Checklist: ##
- [ ] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

## Related Pivotal Tracker stories ##
[164047016](https://www.pivotaltracker.com/story/show/164047016)

## Reviewers ##
- @andela/olympian-devs
- @mnswaleh 
- @Kibetchirchir 
- @kelvinndmo 
- @JumaKahiga 
- @winniekariuki @Derrickkip

### CODE REVIEW

**Review by Kibetchirchir — DISMISSED** [review]
Good work

**Review by kelvinndmo — DISMISSED** [review]

**Comment by mnswaleh** [comment]
Kindly edit your reviewers  list on your comment

**Comment by kelvinndmo** [comment]
Kindly check on one of your commit messages and ensure it meets the Andela Engineering guide standards otherwise everything else is good to go once this is fixed.

**Comment by mnswaleh** [comment]
Sorry, I also forgot to mention that App.js in src folder is same as Home.js in components. It would also help if you create a CSS folder and move the tests folder into src

**Review by Kibetchirchir — APPROVED** [review]

**Review by mnswaleh — APPROVED** [review]

**Pull request merged**
